### ISSUE TITLE
Настройки окружения

### ISSUE THREAD

**Issue by nashoboima** [BombinS/AFDX_issue#1]
1. Не получается задать label для issues
2. Не к чему привязывать issues

**Comment by BombinS** [comment]
ну вот я добавил Label "bug" ^)

**Comment by nashoboima** [comment]
Я не могу присваивать?
Тут чат есть?
 Надо обучалку пройти какую-нибудь

**Comment by BombinS** [comment]
:)
да надо бы (про обучалку)
сам разбираюсь

**Comment by BombinS** [comment]
че то странноватая штука все таки... не совсем понимаю за что ее хвалят...
